spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyencaotri26092003@gmail.com
    password: ThucAnh150109**
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
